<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="旅程资讯"
           tests="11"
           failures="1"
           errors="0"
           skipped="0"
           time="61.277">
  <properties />
            <testcase name="test1" time="4.380" classname="com.winsion.inception.test.Lczx">
                <failure type="java.lang.AssertionError"
                  message="expected [成都铁路局关于2016年5月6、7日部分旅客列车调整运行线路的公告] but found [太原铁路局关于5月8日K505次列车停运的公告]"
              >
<![CDATA[java.lang.AssertionError: expected [成都铁路局关于2016年5月6、7日部分旅客列车调整运行线路的公告] but found [太原铁路局关于5月8日K505次列车停运的公告]
  org.testng.Assert.fail(Assert.java:94)
  org.testng.Assert.failNotEquals(Assert.java:494)
  org.testng.Assert.assertEquals(Assert.java:123)
  org.testng.Assert.assertEquals(Assert.java:176)
  org.testng.Assert.assertEquals(Assert.java:186)
  com.winsion.inception.test.Lczx.test1(Lczx.java:78)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.lang.reflect.Method.invoke(Method.java:483)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
  org.testng.TestRunner.privateRun(TestRunner.java:767)
  org.testng.TestRunner.run(TestRunner.java:617)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:335)
  org.testng.SuiteRunner.access$000(SuiteRunner.java:37)
  org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:369)
  org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
  java.util.concurrent.FutureTask.run(FutureTask.java:266)
  java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  java.lang.Thread.run(Thread.java:744)
]]>
      </failure>

          </testcase>
  
  
            <testcase name="test2" time="4.640" classname="com.winsion.inception.test.Lczx" />
                <testcase name="test2" time="6.967" classname="com.winsion.inception.test.Lczx" />
                <testcase name="test2" time="5.883" classname="com.winsion.inception.test.Lczx" />
                <testcase name="test2" time="6.975" classname="com.winsion.inception.test.Lczx" />
                <testcase name="test2" time="7.168" classname="com.winsion.inception.test.Lczx" />
                <testcase name="test1" time="3.164" classname="com.winsion.inception.test.Lczx" />
                <testcase name="test2" time="5.438" classname="com.winsion.inception.test.Lczx" />
                <testcase name="test2" time="7.933" classname="com.winsion.inception.test.Lczx" />
                <testcase name="test1" time="3.754" classname="com.winsion.inception.test.Lczx" />
                <testcase name="test2" time="4.975" classname="com.winsion.inception.test.Lczx" />
      
</testsuite>
