<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="按行程添加"
           tests="2"
           failures="1"
           errors="0"
           skipped="0"
           time="115.160">
  <properties />
            <testcase name="test1" time="55.603" classname="com.winsion.inception.test.Addtrain2">
                <failure type="java.lang.AssertionError"
                  message="Lists differ at element [1]: 已出发 != 正在候车 expected [已出发] but found [正在候车]"
              >
<![CDATA[java.lang.AssertionError: Lists differ at element [1]: 已出发 != 正在候车 expected [已出发] but found [正在候车]
  org.testng.Assert.fail(Assert.java:94)
  org.testng.Assert.failNotEquals(Assert.java:494)
  org.testng.Assert.assertEquals(Assert.java:123)
  org.testng.Assert.assertEquals(Assert.java:549)
  org.testng.Assert.assertEquals(Assert.java:668)
  org.testng.Assert.assertEquals(Assert.java:725)
  com.winsion.inception.test.Addtrain2.test1(Addtrain2.java:72)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.lang.reflect.Method.invoke(Method.java:483)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
  java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  java.lang.Thread.run(Thread.java:744)
]]>
      </failure>

          </testcase>
  
  
            <testcase name="test2" time="59.557" classname="com.winsion.inception.test.Addtrain2" />
      
</testsuite>
