<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="再次进件不出合同测试流程"
           tests="12"
           failures="1"
           errors="0"
           skipped="0"
           time="437.597">
  <properties />
            <testcase name="test9" time="17.322" classname="com.kuaishoudan.financer.test.Test4">
                <failure type="java.lang.AssertionError"
                  message="Maps do not match for key:insurance actual:485090.53 expected:485090.52 expected [485090.52] but found [485090.53]"
              >
<![CDATA[java.lang.AssertionError: Maps do not match for key:insurance actual:485090.53 expected:485090.52 expected [485090.52] but found [485090.53]
  org.testng.Assert.fail(Assert.java:94)
  org.testng.Assert.failNotEquals(Assert.java:494)
  org.testng.Assert.assertEquals(Assert.java:123)
  org.testng.Assert.assertEquals(Assert.java:835)
  com.kuaishoudan.financer.test.Test4.test9(Test4.java:154)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.lang.reflect.Method.invoke(Method.java:498)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
  org.testng.TestRunner.privateRun(TestRunner.java:767)
  org.testng.TestRunner.run(TestRunner.java:617)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:335)
  org.testng.SuiteRunner.access$000(SuiteRunner.java:37)
  org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:369)
  org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
  java.util.concurrent.FutureTask.run(FutureTask.java:266)
  java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  java.lang.Thread.run(Thread.java:745)
]]>
      </failure>

          </testcase>
  
  
            <testcase name="test5" time="6.928" classname="com.kuaishoudan.financer.test.Test4" />
                <testcase name="test10" time="14.495" classname="com.kuaishoudan.financer.test.Test4" />
                <testcase name="test8" time="103.018" classname="com.kuaishoudan.financer.test.Test4" />
                <testcase name="test13" time="27.335" classname="com.kuaishoudan.financer.test.Test4" />
                <testcase name="test12" time="25.393" classname="com.kuaishoudan.financer.test.Test4" />
                <testcase name="test14" time="71.768" classname="com.kuaishoudan.financer.test.Test4" />
                <testcase name="test4" time="7.996" classname="com.kuaishoudan.financer.test.Test4" />
                <testcase name="test11" time="15.272" classname="com.kuaishoudan.financer.test.Test4" />
                <testcase name="test15" time="14.747" classname="com.kuaishoudan.financer.test.Test4" />
                <testcase name="test2" time="117.134" classname="com.kuaishoudan.financer.test.Test4" />
                <testcase name="test3" time="16.189" classname="com.kuaishoudan.financer.test.Test4" />
      
</testsuite>
